import { GoogleGenAI } from "@google/genai";
import { BaseTool } from './base-tool';
import { ToolResult, ImageGenerationRequest } from '@/lib/types/agent-types';
import { EnvironmentConfig } from '@/lib/config/environment';

export class ImageGenerationTool extends BaseTool {
  private gemini: GoogleGenAI;

  constructor(private config: EnvironmentConfig) {
    super();
    this.gemini = new GoogleGenAI({
      apiKey: config.geminiApiKey
    });
  }

  async execute(params: ImageGenerationRequest, _context?: unknown): Promise<ToolResult> {
    try {
      const model = params.model || this.selectModel(params.style, params.quality);
      const result = await this.generateImage(model, params);
      
      return this.createResult(true, {
        images: result.images,
        prompt: params.prompt,
        model: model,
        seed: params.seed,
      }, undefined, {
        model: model,
        imageCount: result.images?.length || 0
      });
    } catch (error) {
      return this.createResult(false, undefined, error instanceof Error ? error.message : 'Image generation failed');
    }
  }

  private selectModel(style?: string, quality?: string): string {
    // Select appropriate Gemini model based on requirements
    if (quality === 'ultra' || quality === 'high' || style === 'photorealistic') {
      return 'gemini-3-pro-image-preview';
    }
    
    if (style === 'artistic' || style === 'creative') {
      return 'gemini-3.1-flash-image-preview';
    }
    
    if (style === 'fast' || quality === 'draft') {
      return 'gemini-2.5-flash-image';
    }
    
    // Default to balanced model
    return 'gemini-3.1-flash-image-preview';
  }

  private async generateImage(model: string, params: ImageGenerationRequest): Promise<{
    images: Array<{ url: string; width?: number; height?: number }>;
  }> {
    // According to Gemini 3 documentation, we use generateContent with imageConfig for Nano Banana models
    // This fixes the 404 error seen with generateImages
    const response = await this.gemini.models.generateContent({
      model: model,
      contents: params.prompt,
      config: {
        // cast to any because the preview SDK types might not have all ImageConfig fields yet
        imageConfig: {
          numberOfImages: params.numImages || 1,
          aspectRatio: params.aspectRatio || '1:1',
        } as any
      }
    });

    const candidate = response.candidates?.[0];
    if (!candidate || !candidate.content || !candidate.content.parts) {
      throw new Error('No image was generated by the model');
    }

    // Convert generated images to data URLs for the frontend
    const images: Array<{ url: string; width?: number; height?: number }> = [];
    
    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        const base64Data = part.inlineData.data;
        const mimeType = part.inlineData.mimeType || (params.format === 'png' ? 'image/png' : 'image/jpeg');
        
        images.push({
          url: `data:${mimeType};base64,${base64Data}`,
          width: params.width,
          height: params.height
        });
      }
    }

    if (images.length === 0) {
      throw new Error('No image data found in the model response');
    }

    return { images };
  }
}
